# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]

path: '/home/asani/Documents/Hi_Paris_Code_Projects/Pyronear/pyro-mlops/datasets/pyronear'
# path: './datasets/pyronear'

train: images/train
val: images/val

# number of classes
nc: 1

# class names (no label for background since yolo already detects it)
names:
  0: smoke



